# -*- coding: utf-8 -*-
{
    'name': 'Student Info',
    'version': '1.0',
    'category': 'Hidden',
    'description': """Student Info CRUD""",
    'author': 'John Doe (john@doe.com)',
    'website': 'www.johndoe.com',
    'license': 'AGPL-3',
    'depends': ['web'],
    'init_xml': [],
    'demo_xml': [],
    'active': False,
    'installable': True,
    'js': ['static/js/*.js'],
    'css': ['static/css/*.css'],
    'update_xml':['student_workflow.xml'],
    'data': ['student_info_view.xml',
            'menu.xml',],
    'qweb': ['static/xml/*.xml'],
}
